WindowManager:
    MainWindow:
    SecondWindow:
    ThirdWindow:
    FourthWindow:

<MainWindow>:
    name: "main"

    GridLayout:
        cols:1

        Label:
            text: "Choose what movie to watch"

        Button:
            text: "Set your preferences."
            on_release:
                app.root.current = "input" 
                root.manager.transition.direction = "left"
        Button:
            text: "Set the Importance of your preferences."
            on_release:
                app.root.current = "light" 
                root.manager.transition.direction = "left"
        Button:
            text: "Results from set inputs."
            on_release:
                app.root.current = "record" 
                root.manager.transition.direction = "left"


<SecondWindow>:
    name: "input"
    GridLayout:
        cols: 1
        Label:
            text:"How much time do you have?"
        
        TextInput:
            text: ""
        
        Label:
            text: "What genre would you like?"
        
        ToggleButton:
            text: "Horror"
        
        ToggleButton:
            text: "Drama"
        
        ToggleButton:
            text: "Animation"
        
        Label:
            text: "Minimum Rating"
                
        
                
        Button:
            text: "Back"
            on_release:
                app.root.current = "main"
                root.manager.transition.direction = "right"
        
<ThirdWindow>:
    name: "light"
    GridLayout:
        cols:1
        
        Button:
            text: "Back"
            on_release:
                app.root.current = "main"
                root.manager.transition.direction = "right"
  

<FourthWindow>:
    name: "record"
    GridLayout:
        cols:1
        
        Button:
            text: "Back"
            on_release:
                app.root.current = "main"
                root.manager.transition.direction = "right"
